### PR TITLE
PAAS-7667 add -y to make cache

### PR DESCRIPTION
**Pull request by brianlieberman**

### CODE REVIEW

**Comment by paas-api-pr-manager** [comment]
Jira Tickets included in PR are:

* [PAAS-7667](https://jira.gannett.com/browse/PAAS-7667): compile dead record stats from NS1 
```
As a PaaS engineer I want to compile the unused records from NS1 and put together a report

 

Acceptance: data collected from NS1 and spreadsheet created
```

**Comment by brianlieberman** [comment]
test this please

**Comment by brianlieberman** [comment]
test this please

**Comment by brianlieberman** [comment]
test this please

**Comment by brianlieberman** [comment]
retest this please

**Review by dthorsen — APPROVED** [review]

**Pull request merged**
